### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by serapath** [cabal-club/cable#1]
Heya :-)

I read through the protocol and it looks quite interesting. I like the goals too. I have a few questions if you dont mind.

1. how do data responses in general (or specifically a `channel list` response) look like?
    2. Do they contain at least a single (latest?) hash for the latest message/post for peers to anchor join msgs?
2. Are `join` and `leave` messages just for politeness or should others ignore posts until they see a join?
4. Do time range requests usually return `text`, `topic`,`join`,`leave`,`info` messages without the ones deleted?
    * can you filter them based on being part of a specific "conversation thread"?
    * or to only include messages from specific peers?
5. Do channel state requests only ask for `topic`,`join`,`leave`,`info` messages without the ones deleted?
   * do they include `text`? (***it is not mentioned in the readme***)
    * can I filter them (history and live) to only include messages from specific peers?
6. Is it planned to allow to query sparsly for the current list of (active) peers in a channel?
7. Is there a size limit when it comes to state fields? `{ name, blocks, hides, max_age }`
  * would people list e.g. a hyperdrive for larger files?

**Also:**
> Most post types will link to the most recent post in a channel from any user (from their perspective) but self-actions such as naming or moderation will link to the most recent self-action.

Was it considered to allow posts with more than one back `link` to enable topological sorting and requests?
* a text message could be a response to multiple messages at once ...some kind of `"merge text message"`
* the `delete` message already has at least two back links as far as i can see (`link` and `hash`)

I imagine that could allow:
* to respond to specific earlier messages of one or more threads.
* to sparsly find out the latest `name` of a peers state without downloading all their state messages?

**Comment by hackergrrl** [comment]
Hopefully the updates to the spec posted since you posted this answer your Qs! It's become much more explicit :)
