### ISSUE TITLE
post header: move timestamp to be header field 5

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cable#12]
was spending the morning getting reacquainted with the spec and a facet of the [post types](https://github.com/cabal-club/cable#post) stood out to me. timestamp is present in all posts, but the position it has in a post depends on the message type. e.g. for `post/text` it is field 7, after `channel_size` + `channel`, while for `post/delete` it is field 5, after the post header's always present 4 fields.

since it seems reasonable that any type of post will contain timestamp information, i think we should make it part of the post header as header field 5. imo this could make it easier for implementors, since its position doesn't arbitrarily shift depending on the particular post type—consistency 👌

**Comment by hackergrrl** [comment]
This makes sense to me. Worst case for posts that don't use timestamp is one wasted byte.
