### ISSUE TITLE
Time? Whose?

### ISSUE THREAD

**Issue by garbados** [cabal-club/cable#2]
Regarding time range queries, should peers just optimistically trust each other's clocks (bad idea) or is there another approach implied?

**Comment by serapath** [comment]
I wonder too.

I think the hash `link` field to reference older messages.
Maybe it should allow multiple "`links`" to enable merge messages.
The `post/delete` already has two, a `link` and a `hash` too

But anyway - that's already some sort of topological time sort, right?

=> So, if many messages happened, then depending on which peers you choose to trust or not, you could check messages which according to their "topological sorting" happened at a similar time and then compare the timestamps (e.g. take the mean time stamp?)

**Comment by serapath** [comment]
Also, at least in post messages (the ones that represent **writes** and matter), the `public_key` could represent a hypercore too. If messages need a `nonce`, those could then be hypercore chunk indexes, because combined with the pubkey, they are unique

**Comment by okdistribute** [comment]
Typically you could record a time sent and time received, but with the `links` we are creating a directed graph, so these records aren't used for ordering messages, the graph is. the timestamps then are simply for user convenience

**Comment by garbados** [comment]
Fair enough. Closing this issue...
