### ISSUE TITLE
Room: Channel

### ISSUE THREAD

**Issue by ghost** [cabal-club/cable#29]
> decentralized local-first peer-to-peer group chat (like IRC/Slack)

It's not like Slack. Discord
cable You have to create multiple Rooms which is bad

# need to be realized
> cable Simply join the Room invite link and the following channels will be available. 
Instead of creating a link for every # channel. 

cable   # Room.  
`#cable_news` # is Channel or Thread
`#general` # is Channel or Thread 
`#cableDev` # is Channel or Thread 
`#cableBug` # is Channel or Thread

**Comment by cblgh** [comment]
looking at this filer's profile, it's newly created and seems to primarily spam many different projects with vaguely nonsensical issues
