### ISSUE TITLE
add version number query

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cable#9]
version numbers in protocols alleviate upgrading after serious use unveils necessary improvements, adding them to cable (based on the version bumps we've had with cabal proper) seems like it could be a win.

one option for cable would be adding a version number as part of the cable frame (alongside e.g. signatures). the downside of this is that all messages are bloated by the few bytes. another option would be to add a handshake / introduction to cable. this second option has the seeming drawback of introducing connection state into what i think is an otherwise state-less protocol; more complexity for marginal up-front gain.

another avenue of approach could be to introduce a general version number query, where clients respond with what version of cable they are running as far as they know. this could see additional utility when combined with cable's [subprotocols](#8), such that the version number query returns a key:val list of `subprotocol:version number` instead of just a single version number for cable.

**Comment by hackergrrl** [comment]
This is a good point. I think we need both of these: *protocol* versioning and *post* versioning. We're definitely not going to get everything right on the first try. 🙃 

I like the idea of exchanging protocol version #s during handshake, primarily because even if we end up changing something very fundamental, like the shape of request headers, peers will know right away they aren't compatible with each other. This would mean us adding wire protocol for said initial handshake.

I think it would be reasonable to add one byte to the post header. Given the header's current size (129+ bytes), another byte only makes it 0.78% larger!

**Comment by hackergrrl** [comment]
Another option, I'm realizing, is to treat `msg_type` as a version. So a `msg_type=1` message will ALWAYS look the way it's specified in the spec, as a `data response`, but of course that doesn't prevent us from specifying a `data response v2` message type with a larger `msg_type` value that works differently. The same idea applies for post types.

This would prevent old nodes from breaking, and adds no extra data overhead. A downside is that a pair of peers will have no *explicit* knowledge that they're on different versions, but one side can *infer* they are when they receive a message of a type they aren't familiar with.

This logic also applies in the event that a message or post type has a security vulnerability discovered in it, where newer clients can choose to ignore older post and message types that are known to be deprecated and have newer replacement versions. Like the previous situation, here the *newer* client will detect there is a compatibility mismatch when they receive deprecated messages or posts.

**Comment by hackergrrl** [comment]
If we treat each message type definition as immutable (i.e. `msg_type=1` will ALWAYS have the given binary format), we don't need *any* other versioning across the protocol, right? Right now the cable protocol is made up exclusively from messages and posts, and if both are implicitly versioned, we're done, right?

I do think that, if we have a handshake specification, *that* ought to be versioned!

**Comment by cblgh** [comment]
we have a handshake with versioning now :) https://github.com/cabal-club/cable/blob/main/handshake.md
